// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// more_area
double more_area(NumericVector x_int, NumericVector y_int, NumericVector radiuses, IntegerMatrix circles);
RcppExport SEXP eulerr_more_area(SEXP x_intSEXP, SEXP y_intSEXP, SEXP radiusesSEXP, SEXP circlesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_int(x_intSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_int(y_intSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type radiuses(radiusesSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type circles(circlesSEXP);
    rcpp_result_gen = Rcpp::wrap(more_area(x_int, y_int, radiuses, circles));
    return rcpp_result_gen;
END_RCPP
}
