# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intersect_ellipses <- function(par, circles) {
    .Call(`_eulerr_intersect_ellipses`, par, circles)
}

optim_final_loss <- function(par, areas, circles) {
    .Call(`_eulerr_optim_final_loss`, par, areas, circles)
}

optim_init_loss <- function(par, d, disjoint, contained) {
    .Call(`_eulerr_optim_init_loss`, par, d, disjoint, contained)
}

optim_init_grad <- function(par, d, disjoint, contained) {
    .Call(`_eulerr_optim_init_grad`, par, d, disjoint, contained)
}

choose_two <- function(x) {
    .Call(`_eulerr_choose_two`, x)
}

bit_indexr <- function(n) {
    .Call(`_eulerr_bit_indexr`, n)
}

discdisc <- function(r1, r2, d) {
    .Call(`_eulerr_discdisc`, r1, r2, d)
}

find_surrounding_sets <- function(xs, ys, x, y, r) {
    .Call(`_eulerr_find_surrounding_sets`, xs, ys, x, y, r)
}

max_colmins <- function(x) {
    .Call(`_eulerr_max_colmins`, x)
}

venneuler_stress <- function(areas, fit) {
    .Call(`_eulerr_venneuler_stress`, areas, fit)
}

closest_point <- function(a, b, x, y) {
    .Call(`_eulerr_closest_point`, a, b, x, y)
}

