# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bit_index <- function(n) {
    .Call('eulerr_bit_index', PACKAGE = 'eulerr', n)
}

return_intersections <- function(par) {
    .Call('eulerr_return_intersections', PACKAGE = 'eulerr', par)
}

venneuler_stress <- function(areas, fit) {
    .Call('eulerr_venneuler_stress', PACKAGE = 'eulerr', areas, fit)
}

loss_final <- function(par, areas) {
    .Call('eulerr_loss_final', PACKAGE = 'eulerr', par, areas)
}

choose_two <- function(x) {
    .Call('eulerr_choose_two', PACKAGE = 'eulerr', x)
}

discdisc <- function(r1, r2, d) {
    .Call('eulerr_discdisc', PACKAGE = 'eulerr', r1, r2, d)
}

