# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

intersect_ellipses <- function(par, circle) {
    .Call(`_eulerr_intersect_ellipses`, par, circle)
}

optim_final_loss <- function(par, areas, circle) {
    .Call(`_eulerr_optim_final_loss`, par, areas, circle)
}

target_function_ptr <- function(par_in) {
    .Call(`_eulerr_target_function_ptr`, par_in)
}

init_final_loss_fun <- function(areas_in, circle) {
    .Call(`_eulerr_init_final_loss_fun`, areas_in, circle)
}

get_final_loss_ptr <- function() {
    .Call(`_eulerr_get_final_loss_ptr`)
}

optim_init_loss <- function(par, d, disjoint, subset) {
    .Call(`_eulerr_optim_init_loss`, par, d, disjoint, subset)
}

optim_init_grad <- function(par, d, disjoint, subset) {
    .Call(`_eulerr_optim_init_grad`, par, d, disjoint, subset)
}

optim_init_hess <- function(par, d, disjoint, subset) {
    .Call(`_eulerr_optim_init_hess`, par, d, disjoint, subset)
}

locate_centers <- function(h, k, a, b, phi, fitted) {
    .Call(`_eulerr_locate_centers`, h, k, a, b, phi, fitted)
}

choose_two <- function(x) {
    .Call(`_eulerr_choose_two`, x)
}

discdisc <- function(d, r1, r2, overlap) {
    .Call(`_eulerr_discdisc`, d, r1, r2, overlap)
}

stress <- function(areas, fit) {
    .Call(`_eulerr_stress`, areas, fit)
}

bit_index_cpp <- function(n) {
    .Call(`_eulerr_bit_index_cpp`, n)
}

